//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  about: About;
  aboutConnection: AboutConnection;
  cv: Cv;
  cvConnection: CvConnection;
  research: Research;
  researchConnection: ResearchConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryCvArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCvConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CvFilter>;
};


export type QueryResearchArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearchConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  about?: InputMaybe<AboutFilter>;
  cv?: InputMaybe<CvFilter>;
  research?: InputMaybe<ResearchFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | About | Cv | Research | Folder;

export type HomeStats = {
  __typename?: 'HomeStats';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  targetValue?: Maybe<Scalars['Float']['output']>;
  prefix?: Maybe<Scalars['String']['output']>;
  suffix?: Maybe<Scalars['String']['output']>;
};

export type HomeFeatures = {
  __typename?: 'HomeFeatures';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  heroTitle?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<HomeStats>>>;
  features?: Maybe<Array<Maybe<HomeFeatures>>>;
  missionHeading?: Maybe<Scalars['String']['output']>;
  missionSubtext?: Maybe<Scalars['String']['output']>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaSubtext?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type HomeStatsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  targetValue?: InputMaybe<NumberFilter>;
  prefix?: InputMaybe<StringFilter>;
  suffix?: InputMaybe<StringFilter>;
};

export type HomeFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  stats?: InputMaybe<HomeStatsFilter>;
  features?: InputMaybe<HomeFeaturesFilter>;
  missionHeading?: InputMaybe<StringFilter>;
  missionSubtext?: InputMaybe<StringFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaSubtext?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type AboutPersonalValues = {
  __typename?: 'AboutPersonalValues';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutKeyAchievements = {
  __typename?: 'AboutKeyAchievements';
  year?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroBio1?: Maybe<Scalars['String']['output']>;
  heroBio2?: Maybe<Scalars['String']['output']>;
  personalValues?: Maybe<Array<Maybe<AboutPersonalValues>>>;
  keyAchievements?: Maybe<Array<Maybe<AboutKeyAchievements>>>;
  journeyEarlyFoundations?: Maybe<Scalars['String']['output']>;
  journeyAcademicCalling?: Maybe<Scalars['String']['output']>;
  journeyTodaysMission?: Maybe<Scalars['String']['output']>;
  journeyQuote?: Maybe<Scalars['String']['output']>;
  journeyClosing?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutPersonalValuesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutKeyAchievementsFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroBio1?: InputMaybe<StringFilter>;
  heroBio2?: InputMaybe<StringFilter>;
  personalValues?: InputMaybe<AboutPersonalValuesFilter>;
  keyAchievements?: InputMaybe<AboutKeyAchievementsFilter>;
  journeyEarlyFoundations?: InputMaybe<StringFilter>;
  journeyAcademicCalling?: InputMaybe<StringFilter>;
  journeyTodaysMission?: InputMaybe<StringFilter>;
  journeyQuote?: InputMaybe<StringFilter>;
  journeyClosing?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type CvEducation = {
  __typename?: 'CvEducation';
  degree?: Maybe<Scalars['String']['output']>;
  institution?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
  committee?: Maybe<Scalars['String']['output']>;
  honors?: Maybe<Scalars['String']['output']>;
};

export type CvCurrentPositions = {
  __typename?: 'CvCurrentPositions';
  title?: Maybe<Scalars['String']['output']>;
  institution?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
};

export type CvRecentAwards = {
  __typename?: 'CvRecentAwards';
  title?: Maybe<Scalars['String']['output']>;
  organization?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type CvMajorGrants = {
  __typename?: 'CvMajorGrants';
  title?: Maybe<Scalars['String']['output']>;
  agency?: Maybe<Scalars['String']['output']>;
  amount?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
};

export type CvPublicationHighlights = {
  __typename?: 'CvPublicationHighlights';
  title?: Maybe<Scalars['String']['output']>;
  journal?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  impact?: Maybe<Scalars['String']['output']>;
  coauthor?: Maybe<Scalars['String']['output']>;
};

export type Cv = Node & Document & {
  __typename?: 'Cv';
  googleDocViewUrl?: Maybe<Scalars['String']['output']>;
  googleDocPdfUrl?: Maybe<Scalars['String']['output']>;
  researchInterests?: Maybe<Scalars['String']['output']>;
  education?: Maybe<Array<Maybe<CvEducation>>>;
  currentPositions?: Maybe<Array<Maybe<CvCurrentPositions>>>;
  keyAffiliations?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  recentAwards?: Maybe<Array<Maybe<CvRecentAwards>>>;
  majorGrants?: Maybe<Array<Maybe<CvMajorGrants>>>;
  publicationHighlights?: Maybe<Array<Maybe<CvPublicationHighlights>>>;
  professionalOrgs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CvEducationFilter = {
  degree?: InputMaybe<StringFilter>;
  institution?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
  committee?: InputMaybe<StringFilter>;
  honors?: InputMaybe<StringFilter>;
};

export type CvCurrentPositionsFilter = {
  title?: InputMaybe<StringFilter>;
  institution?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
};

export type CvRecentAwardsFilter = {
  title?: InputMaybe<StringFilter>;
  organization?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type CvMajorGrantsFilter = {
  title?: InputMaybe<StringFilter>;
  agency?: InputMaybe<StringFilter>;
  amount?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type CvPublicationHighlightsFilter = {
  title?: InputMaybe<StringFilter>;
  journal?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  impact?: InputMaybe<StringFilter>;
  coauthor?: InputMaybe<StringFilter>;
};

export type CvFilter = {
  googleDocViewUrl?: InputMaybe<StringFilter>;
  googleDocPdfUrl?: InputMaybe<StringFilter>;
  researchInterests?: InputMaybe<StringFilter>;
  education?: InputMaybe<CvEducationFilter>;
  currentPositions?: InputMaybe<CvCurrentPositionsFilter>;
  keyAffiliations?: InputMaybe<StringFilter>;
  recentAwards?: InputMaybe<CvRecentAwardsFilter>;
  majorGrants?: InputMaybe<CvMajorGrantsFilter>;
  publicationHighlights?: InputMaybe<CvPublicationHighlightsFilter>;
  professionalOrgs?: InputMaybe<StringFilter>;
};

export type CvConnectionEdges = {
  __typename?: 'CvConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Cv>;
};

export type CvConnection = Connection & {
  __typename?: 'CvConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CvConnectionEdges>>>;
};

export type ResearchResearchAreas = {
  __typename?: 'ResearchResearchAreas';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  publications?: Maybe<Scalars['Float']['output']>;
  color?: Maybe<Scalars['String']['output']>;
};

export type ResearchCurrentProjects = {
  __typename?: 'ResearchCurrentProjects';
  title?: Maybe<Scalars['String']['output']>;
  funding?: Maybe<Scalars['String']['output']>;
  amount?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  collaborators?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ResearchAppliedProjects = {
  __typename?: 'ResearchAppliedProjects';
  title?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  period?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  impact?: Maybe<Scalars['String']['output']>;
  color?: Maybe<Scalars['String']['output']>;
  outcomes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Research = Node & Document & {
  __typename?: 'Research';
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  researchAreas?: Maybe<Array<Maybe<ResearchResearchAreas>>>;
  currentProjects?: Maybe<Array<Maybe<ResearchCurrentProjects>>>;
  methodologies?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  appliedProjects?: Maybe<Array<Maybe<ResearchAppliedProjects>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResearchResearchAreasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  publications?: InputMaybe<NumberFilter>;
  color?: InputMaybe<StringFilter>;
};

export type ResearchCurrentProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  funding?: InputMaybe<StringFilter>;
  amount?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  collaborators?: InputMaybe<StringFilter>;
};

export type ResearchAppliedProjectsFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  period?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  impact?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  outcomes?: InputMaybe<StringFilter>;
};

export type ResearchFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  researchAreas?: InputMaybe<ResearchResearchAreasFilter>;
  currentProjects?: InputMaybe<ResearchCurrentProjectsFilter>;
  methodologies?: InputMaybe<StringFilter>;
  appliedProjects?: InputMaybe<ResearchAppliedProjectsFilter>;
};

export type ResearchConnectionEdges = {
  __typename?: 'ResearchConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Research>;
};

export type ResearchConnection = Connection & {
  __typename?: 'ResearchConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResearchConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateAbout: About;
  createAbout: About;
  updateCv: Cv;
  createCv: Cv;
  updateResearch: Research;
  createResearch: Research;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateCvArgs = {
  relativePath: Scalars['String']['input'];
  params: CvMutation;
};


export type MutationCreateCvArgs = {
  relativePath: Scalars['String']['input'];
  params: CvMutation;
};


export type MutationUpdateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationCreateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  cv?: InputMaybe<CvMutation>;
  research?: InputMaybe<ResearchMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  cv?: InputMaybe<CvMutation>;
  research?: InputMaybe<ResearchMutation>;
};

export type HomeStatsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  targetValue?: InputMaybe<Scalars['Float']['input']>;
  prefix?: InputMaybe<Scalars['String']['input']>;
  suffix?: InputMaybe<Scalars['String']['input']>;
};

export type HomeFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<HomeStatsMutation>>>;
  features?: InputMaybe<Array<InputMaybe<HomeFeaturesMutation>>>;
  missionHeading?: InputMaybe<Scalars['String']['input']>;
  missionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSubtext?: InputMaybe<Scalars['String']['input']>;
};

export type AboutPersonalValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutKeyAchievementsMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroBio1?: InputMaybe<Scalars['String']['input']>;
  heroBio2?: InputMaybe<Scalars['String']['input']>;
  personalValues?: InputMaybe<Array<InputMaybe<AboutPersonalValuesMutation>>>;
  keyAchievements?: InputMaybe<Array<InputMaybe<AboutKeyAchievementsMutation>>>;
  journeyEarlyFoundations?: InputMaybe<Scalars['String']['input']>;
  journeyAcademicCalling?: InputMaybe<Scalars['String']['input']>;
  journeyTodaysMission?: InputMaybe<Scalars['String']['input']>;
  journeyQuote?: InputMaybe<Scalars['String']['input']>;
  journeyClosing?: InputMaybe<Scalars['String']['input']>;
};

export type CvEducationMutation = {
  degree?: InputMaybe<Scalars['String']['input']>;
  institution?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
  committee?: InputMaybe<Scalars['String']['input']>;
  honors?: InputMaybe<Scalars['String']['input']>;
};

export type CvCurrentPositionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  institution?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type CvRecentAwardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type CvMajorGrantsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  agency?: InputMaybe<Scalars['String']['input']>;
  amount?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type CvPublicationHighlightsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  journal?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  impact?: InputMaybe<Scalars['String']['input']>;
  coauthor?: InputMaybe<Scalars['String']['input']>;
};

export type CvMutation = {
  googleDocViewUrl?: InputMaybe<Scalars['String']['input']>;
  googleDocPdfUrl?: InputMaybe<Scalars['String']['input']>;
  researchInterests?: InputMaybe<Scalars['String']['input']>;
  education?: InputMaybe<Array<InputMaybe<CvEducationMutation>>>;
  currentPositions?: InputMaybe<Array<InputMaybe<CvCurrentPositionsMutation>>>;
  keyAffiliations?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  recentAwards?: InputMaybe<Array<InputMaybe<CvRecentAwardsMutation>>>;
  majorGrants?: InputMaybe<Array<InputMaybe<CvMajorGrantsMutation>>>;
  publicationHighlights?: InputMaybe<Array<InputMaybe<CvPublicationHighlightsMutation>>>;
  professionalOrgs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ResearchResearchAreasMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  publications?: InputMaybe<Scalars['Float']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type ResearchCurrentProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  funding?: InputMaybe<Scalars['String']['input']>;
  amount?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  collaborators?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ResearchAppliedProjectsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  period?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  impact?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  outcomes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ResearchMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  researchAreas?: InputMaybe<Array<InputMaybe<ResearchResearchAreasMutation>>>;
  currentProjects?: InputMaybe<Array<InputMaybe<ResearchCurrentProjectsMutation>>>;
  methodologies?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  appliedProjects?: InputMaybe<Array<InputMaybe<ResearchAppliedProjectsMutation>>>;
};

export type HomePartsFragment = { __typename: 'Home', heroTitle?: string | null, subtitle?: string | null, description?: string | null, missionHeading?: string | null, missionSubtext?: string | null, ctaHeading?: string | null, ctaSubtext?: string | null, stats?: Array<{ __typename: 'HomeStats', number?: string | null, label?: string | null, targetValue?: number | null, prefix?: string | null, suffix?: string | null } | null> | null, features?: Array<{ __typename: 'HomeFeatures', title?: string | null, description?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', heroTitle?: string | null, heroBio1?: string | null, heroBio2?: string | null, journeyEarlyFoundations?: string | null, journeyAcademicCalling?: string | null, journeyTodaysMission?: string | null, journeyQuote?: string | null, journeyClosing?: string | null, personalValues?: Array<{ __typename: 'AboutPersonalValues', title?: string | null, description?: string | null } | null> | null, keyAchievements?: Array<{ __typename: 'AboutKeyAchievements', year?: string | null, title?: string | null, description?: string | null } | null> | null };

export type CvPartsFragment = { __typename: 'Cv', googleDocViewUrl?: string | null, googleDocPdfUrl?: string | null, researchInterests?: string | null, keyAffiliations?: Array<string | null> | null, professionalOrgs?: Array<string | null> | null, education?: Array<{ __typename: 'CvEducation', degree?: string | null, institution?: string | null, year?: string | null, location?: string | null, details?: string | null, committee?: string | null, honors?: string | null } | null> | null, currentPositions?: Array<{ __typename: 'CvCurrentPositions', title?: string | null, institution?: string | null, period?: string | null, location?: string | null, type?: string | null } | null> | null, recentAwards?: Array<{ __typename: 'CvRecentAwards', title?: string | null, organization?: string | null, year?: string | null, description?: string | null } | null> | null, majorGrants?: Array<{ __typename: 'CvMajorGrants', title?: string | null, agency?: string | null, amount?: string | null, period?: string | null, role?: string | null } | null> | null, publicationHighlights?: Array<{ __typename: 'CvPublicationHighlights', title?: string | null, journal?: string | null, year?: string | null, impact?: string | null, coauthor?: string | null } | null> | null };

export type ResearchPartsFragment = { __typename: 'Research', heroTitle?: string | null, heroSubtext?: string | null, methodologies?: Array<string | null> | null, researchAreas?: Array<{ __typename: 'ResearchResearchAreas', title?: string | null, description?: string | null, publications?: number | null, color?: string | null } | null> | null, currentProjects?: Array<{ __typename: 'ResearchCurrentProjects', title?: string | null, funding?: string | null, amount?: string | null, period?: string | null, description?: string | null, collaborators?: Array<string | null> | null } | null> | null, appliedProjects?: Array<{ __typename: 'ResearchAppliedProjects', title?: string | null, category?: string | null, type?: string | null, period?: string | null, location?: string | null, description?: string | null, impact?: string | null, color?: string | null, outcomes?: Array<string | null> | null } | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, heroTitle?: string | null, subtitle?: string | null, description?: string | null, missionHeading?: string | null, missionSubtext?: string | null, ctaHeading?: string | null, ctaSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'HomeStats', number?: string | null, label?: string | null, targetValue?: number | null, prefix?: string | null, suffix?: string | null } | null> | null, features?: Array<{ __typename: 'HomeFeatures', title?: string | null, description?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, heroTitle?: string | null, subtitle?: string | null, description?: string | null, missionHeading?: string | null, missionSubtext?: string | null, ctaHeading?: string | null, ctaSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'HomeStats', number?: string | null, label?: string | null, targetValue?: number | null, prefix?: string | null, suffix?: string | null } | null> | null, features?: Array<{ __typename: 'HomeFeatures', title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, heroTitle?: string | null, heroBio1?: string | null, heroBio2?: string | null, journeyEarlyFoundations?: string | null, journeyAcademicCalling?: string | null, journeyTodaysMission?: string | null, journeyQuote?: string | null, journeyClosing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personalValues?: Array<{ __typename: 'AboutPersonalValues', title?: string | null, description?: string | null } | null> | null, keyAchievements?: Array<{ __typename: 'AboutKeyAchievements', year?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, heroTitle?: string | null, heroBio1?: string | null, heroBio2?: string | null, journeyEarlyFoundations?: string | null, journeyAcademicCalling?: string | null, journeyTodaysMission?: string | null, journeyQuote?: string | null, journeyClosing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, personalValues?: Array<{ __typename: 'AboutPersonalValues', title?: string | null, description?: string | null } | null> | null, keyAchievements?: Array<{ __typename: 'AboutKeyAchievements', year?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type CvQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CvQuery = { __typename?: 'Query', cv: { __typename: 'Cv', id: string, googleDocViewUrl?: string | null, googleDocPdfUrl?: string | null, researchInterests?: string | null, keyAffiliations?: Array<string | null> | null, professionalOrgs?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, education?: Array<{ __typename: 'CvEducation', degree?: string | null, institution?: string | null, year?: string | null, location?: string | null, details?: string | null, committee?: string | null, honors?: string | null } | null> | null, currentPositions?: Array<{ __typename: 'CvCurrentPositions', title?: string | null, institution?: string | null, period?: string | null, location?: string | null, type?: string | null } | null> | null, recentAwards?: Array<{ __typename: 'CvRecentAwards', title?: string | null, organization?: string | null, year?: string | null, description?: string | null } | null> | null, majorGrants?: Array<{ __typename: 'CvMajorGrants', title?: string | null, agency?: string | null, amount?: string | null, period?: string | null, role?: string | null } | null> | null, publicationHighlights?: Array<{ __typename: 'CvPublicationHighlights', title?: string | null, journal?: string | null, year?: string | null, impact?: string | null, coauthor?: string | null } | null> | null } };

export type CvConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CvFilter>;
}>;


export type CvConnectionQuery = { __typename?: 'Query', cvConnection: { __typename?: 'CvConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CvConnectionEdges', cursor: string, node?: { __typename: 'Cv', id: string, googleDocViewUrl?: string | null, googleDocPdfUrl?: string | null, researchInterests?: string | null, keyAffiliations?: Array<string | null> | null, professionalOrgs?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, education?: Array<{ __typename: 'CvEducation', degree?: string | null, institution?: string | null, year?: string | null, location?: string | null, details?: string | null, committee?: string | null, honors?: string | null } | null> | null, currentPositions?: Array<{ __typename: 'CvCurrentPositions', title?: string | null, institution?: string | null, period?: string | null, location?: string | null, type?: string | null } | null> | null, recentAwards?: Array<{ __typename: 'CvRecentAwards', title?: string | null, organization?: string | null, year?: string | null, description?: string | null } | null> | null, majorGrants?: Array<{ __typename: 'CvMajorGrants', title?: string | null, agency?: string | null, amount?: string | null, period?: string | null, role?: string | null } | null> | null, publicationHighlights?: Array<{ __typename: 'CvPublicationHighlights', title?: string | null, journal?: string | null, year?: string | null, impact?: string | null, coauthor?: string | null } | null> | null } | null } | null> | null } };

export type ResearchQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResearchQuery = { __typename?: 'Query', research: { __typename: 'Research', id: string, heroTitle?: string | null, heroSubtext?: string | null, methodologies?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, researchAreas?: Array<{ __typename: 'ResearchResearchAreas', title?: string | null, description?: string | null, publications?: number | null, color?: string | null } | null> | null, currentProjects?: Array<{ __typename: 'ResearchCurrentProjects', title?: string | null, funding?: string | null, amount?: string | null, period?: string | null, description?: string | null, collaborators?: Array<string | null> | null } | null> | null, appliedProjects?: Array<{ __typename: 'ResearchAppliedProjects', title?: string | null, category?: string | null, type?: string | null, period?: string | null, location?: string | null, description?: string | null, impact?: string | null, color?: string | null, outcomes?: Array<string | null> | null } | null> | null } };

export type ResearchConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
}>;


export type ResearchConnectionQuery = { __typename?: 'Query', researchConnection: { __typename?: 'ResearchConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResearchConnectionEdges', cursor: string, node?: { __typename: 'Research', id: string, heroTitle?: string | null, heroSubtext?: string | null, methodologies?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, researchAreas?: Array<{ __typename: 'ResearchResearchAreas', title?: string | null, description?: string | null, publications?: number | null, color?: string | null } | null> | null, currentProjects?: Array<{ __typename: 'ResearchCurrentProjects', title?: string | null, funding?: string | null, amount?: string | null, period?: string | null, description?: string | null, collaborators?: Array<string | null> | null } | null> | null, appliedProjects?: Array<{ __typename: 'ResearchAppliedProjects', title?: string | null, category?: string | null, type?: string | null, period?: string | null, location?: string | null, description?: string | null, impact?: string | null, color?: string | null, outcomes?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  heroTitle
  subtitle
  description
  stats {
    __typename
    number
    label
    targetValue
    prefix
    suffix
  }
  features {
    __typename
    title
    description
  }
  missionHeading
  missionSubtext
  ctaHeading
  ctaSubtext
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  heroTitle
  heroBio1
  heroBio2
  personalValues {
    __typename
    title
    description
  }
  keyAchievements {
    __typename
    year
    title
    description
  }
  journeyEarlyFoundations
  journeyAcademicCalling
  journeyTodaysMission
  journeyQuote
  journeyClosing
}
    `;
export const CvPartsFragmentDoc = gql`
    fragment CvParts on Cv {
  __typename
  googleDocViewUrl
  googleDocPdfUrl
  researchInterests
  education {
    __typename
    degree
    institution
    year
    location
    details
    committee
    honors
  }
  currentPositions {
    __typename
    title
    institution
    period
    location
    type
  }
  keyAffiliations
  recentAwards {
    __typename
    title
    organization
    year
    description
  }
  majorGrants {
    __typename
    title
    agency
    amount
    period
    role
  }
  publicationHighlights {
    __typename
    title
    journal
    year
    impact
    coauthor
  }
  professionalOrgs
}
    `;
export const ResearchPartsFragmentDoc = gql`
    fragment ResearchParts on Research {
  __typename
  heroTitle
  heroSubtext
  researchAreas {
    __typename
    title
    description
    publications
    color
  }
  currentProjects {
    __typename
    title
    funding
    amount
    period
    description
    collaborators
  }
  methodologies
  appliedProjects {
    __typename
    title
    category
    type
    period
    location
    description
    impact
    color
    outcomes
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const CvDocument = gql`
    query cv($relativePath: String!) {
  cv(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CvParts
  }
}
    ${CvPartsFragmentDoc}`;
export const CvConnectionDocument = gql`
    query cvConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CvFilter) {
  cvConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CvParts
      }
    }
  }
}
    ${CvPartsFragmentDoc}`;
export const ResearchDocument = gql`
    query research($relativePath: String!) {
  research(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResearchParts
  }
}
    ${ResearchPartsFragmentDoc}`;
export const ResearchConnectionDocument = gql`
    query researchConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResearchFilter) {
  researchConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResearchParts
      }
    }
  }
}
    ${ResearchPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    cv(variables: CvQueryVariables, options?: C): Promise<{data: CvQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvQueryVariables, query: string}> {
        return requester<{data: CvQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvQueryVariables, query: string}, CvQueryVariables>(CvDocument, variables, options);
      },
    cvConnection(variables?: CvConnectionQueryVariables, options?: C): Promise<{data: CvConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvConnectionQueryVariables, query: string}> {
        return requester<{data: CvConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CvConnectionQueryVariables, query: string}, CvConnectionQueryVariables>(CvConnectionDocument, variables, options);
      },
    research(variables: ResearchQueryVariables, options?: C): Promise<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}> {
        return requester<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}, ResearchQueryVariables>(ResearchDocument, variables, options);
      },
    researchConnection(variables?: ResearchConnectionQueryVariables, options?: C): Promise<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}> {
        return requester<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}, ResearchConnectionQueryVariables>(ResearchConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/625b31e0-dc9a-4bc1-baa9-dc8e69c1e530/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  