import { defineConfig } from "tinacms";

export default defineConfig({
  branch: process.env.GITHUB_BRANCH || process.env.VERCEL_GIT_COMMIT_REF || "main",
  clientId: "625b31e0-dc9a-4bc1-baa9-dc8e69c1e530",
  token: process.env.TINA_TOKEN || "",
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      // ─── HOME PAGE ────────────────────────────────────────────
      {
        name: "home",
        label: "Home Page",
        path: "content",
        format: "json",
        ui: {
          allowedActions: { create: false, delete: false },
          filename: { readonly: true, slugify: () => "home" },
        },
        match: { include: "home" },
        fields: [
          { type: "string", name: "heroTitle", label: "Hero Name / Title" },
          { type: "string", name: "subtitle", label: "Subtitle (e.g. Scholar. Attorney. Advocate.)" },
          { type: "string", name: "description", label: "Hero Description", ui: { component: "textarea" } },
          {
            type: "object",
            name: "stats",
            label: "Stats Bar",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.label }) },
            fields: [
              { type: "string", name: "number", label: "Display Number (e.g. 33+)" },
              { type: "string", name: "label", label: "Label (e.g. Publications)" },
              { type: "number", name: "targetValue", label: "Animated Target Value" },
              { type: "string", name: "prefix", label: "Prefix (e.g. $)" },
              { type: "string", name: "suffix", label: "Suffix (e.g. +)" },
            ],
          },
          {
            type: "object",
            name: "features",
            label: "Mission Cards (Scholar / Attorney / Advocate)",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Card Title" },
              { type: "string", name: "description", label: "Card Description", ui: { component: "textarea" } },
            ],
          },
          { type: "string", name: "missionHeading", label: "Mission Section Heading" },
          { type: "string", name: "missionSubtext", label: "Mission Section Subtext" },
          { type: "string", name: "ctaHeading", label: "CTA Section Heading" },
          { type: "string", name: "ctaSubtext", label: "CTA Section Subtext", ui: { component: "textarea" } },
        ],
      },

      // ─── ABOUT PAGE ───────────────────────────────────────────
      {
        name: "about",
        label: "About Page",
        path: "content",
        format: "json",
        ui: {
          allowedActions: { create: false, delete: false },
          filename: { readonly: true, slugify: () => "about" },
        },
        match: { include: "about" },
        fields: [
          { type: "string", name: "heroTitle", label: "Page Title" },
          { type: "string", name: "heroBio1", label: "Bio Paragraph 1", ui: { component: "textarea" } },
          { type: "string", name: "heroBio2", label: "Bio Paragraph 2", ui: { component: "textarea" } },
          {
            type: "object",
            name: "personalValues",
            label: "Personal Values Cards",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Value Title" },
              { type: "string", name: "description", label: "Value Description", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "keyAchievements",
            label: "Key Milestones",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "year", label: "Year" },
              { type: "string", name: "title", label: "Achievement Title" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
            ],
          },
          { type: "string", name: "journeyEarlyFoundations", label: "Journey: Early Foundations", ui: { component: "textarea" } },
          { type: "string", name: "journeyAcademicCalling", label: "Journey: Academic Calling", ui: { component: "textarea" } },
          { type: "string", name: "journeyTodaysMission", label: "Journey: Today's Mission", ui: { component: "textarea" } },
          { type: "string", name: "journeyQuote", label: "Journey: Blockquote", ui: { component: "textarea" } },
          { type: "string", name: "journeyClosing", label: "Journey: Closing Line", ui: { component: "textarea" } },
        ],
      },

      // ─── CV PAGE ──────────────────────────────────────────────
      {
        name: "cv",
        label: "CV Page",
        path: "content",
        format: "json",
        ui: {
          allowedActions: { create: false, delete: false },
          filename: { readonly: true, slugify: () => "cv" },
        },
        match: { include: "cv" },
        fields: [
          { type: "string", name: "googleDocViewUrl", label: "Google Doc — View URL (for 'View CV Online' button)" },
          { type: "string", name: "googleDocPdfUrl", label: "Google Doc — PDF Export URL (for 'Download CV' button)" },
          { type: "string", name: "researchInterests", label: "Research Interests", ui: { component: "textarea" } },
          {
            type: "object",
            name: "education",
            label: "Education",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.degree }) },
            fields: [
              { type: "string", name: "degree", label: "Degree" },
              { type: "string", name: "institution", label: "Institution" },
              { type: "string", name: "year", label: "Year" },
              { type: "string", name: "location", label: "Location" },
              { type: "string", name: "details", label: "Details / Dissertation", ui: { component: "textarea" } },
              { type: "string", name: "committee", label: "Committee Members", ui: { component: "textarea" } },
              { type: "string", name: "honors", label: "Honors / Awards for this degree", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "currentPositions",
            label: "Current Positions",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Job Title" },
              { type: "string", name: "institution", label: "Institution / Department", ui: { component: "textarea" } },
              { type: "string", name: "period", label: "Period (e.g. June 2022 – present)" },
              { type: "string", name: "location", label: "Location" },
              {
                type: "string",
                name: "type",
                label: "Display Type",
                options: ["primary", "secondary"],
              },
            ],
          },
          {
            type: "string",
            name: "keyAffiliations",
            label: "Key Affiliations",
            list: true,
            ui: { component: "textarea" },
          },
          {
            type: "object",
            name: "recentAwards",
            label: "Awards & Honors",
            list: true,
            ui: { itemProps: (item: any) => ({ label: `${item.year} – ${item.title}` }) },
            fields: [
              { type: "string", name: "title", label: "Award Title" },
              { type: "string", name: "organization", label: "Organization" },
              { type: "string", name: "year", label: "Year" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "majorGrants",
            label: "Grants & Funding",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Grant Title" },
              { type: "string", name: "agency", label: "Funding Agency" },
              { type: "string", name: "amount", label: "Amount (e.g. $184,744)" },
              { type: "string", name: "period", label: "Period (e.g. 2024–2027)" },
              { type: "string", name: "role", label: "Your Role (e.g. Principal Investigator)" },
            ],
          },
          {
            type: "object",
            name: "publicationHighlights",
            label: "Featured Publications",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title?.substring(0, 60) + "..." }) },
            fields: [
              { type: "string", name: "title", label: "Publication Title", ui: { component: "textarea" } },
              { type: "string", name: "journal", label: "Journal Name" },
              { type: "string", name: "year", label: "Year (or 'In press')" },
              { type: "string", name: "impact", label: "Impact Factor (e.g. 5-Year IF: 3.4)" },
              { type: "string", name: "coauthor", label: "Co-authors (leave blank if solo)" },
            ],
          },
          {
            type: "string",
            name: "professionalOrgs",
            label: "Professional Memberships",
            list: true,
          },
        ],
      },

      // ─── RESEARCH PAGE ────────────────────────────────────────
      {
        name: "research",
        label: "Research Page",
        path: "content",
        format: "json",
        ui: {
          allowedActions: { create: false, delete: false },
          filename: { readonly: true, slugify: () => "research" },
        },
        match: { include: "research" },
        fields: [
          { type: "string", name: "heroTitle", label: "Page Title" },
          { type: "string", name: "heroSubtext", label: "Page Subtitle", ui: { component: "textarea" } },
          {
            type: "object",
            name: "researchAreas",
            label: "Research Areas",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Area Title" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
              { type: "number", name: "publications", label: "Number of Publications" },
              {
                type: "string",
                name: "color",
                label: "Color Theme",
                options: [
                  "from-amber-500 to-orange-600",
                  "from-rose-500 to-pink-600",
                  "from-emerald-500 to-teal-600",
                  "from-purple-500 to-indigo-600",
                  "from-green-500 to-emerald-600",
                  "from-stone-600 to-stone-700",
                ],
              },
            ],
          },
          {
            type: "object",
            name: "currentProjects",
            label: "Current Research Projects",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Project Title" },
              { type: "string", name: "funding", label: "Funding Source" },
              { type: "string", name: "amount", label: "Amount (e.g. $450,000)" },
              { type: "string", name: "period", label: "Period (e.g. 2023-2026)" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
              { type: "string", name: "collaborators", label: "Collaborators", list: true },
            ],
          },
          {
            type: "string",
            name: "methodologies",
            label: "Research Methodologies",
            list: true,
          },
          {
            type: "object",
            name: "appliedProjects",
            label: "Applied Projects",
            list: true,
            ui: { itemProps: (item: any) => ({ label: item.title }) },
            fields: [
              { type: "string", name: "title", label: "Project Title" },
              {
                type: "string",
                name: "category",
                label: "Category",
                options: ["academic", "research", "advocacy", "community"],
              },
              { type: "string", name: "type", label: "Type Label (e.g. Research Initiative)" },
              { type: "string", name: "period", label: "Period (e.g. 2022 - Present)" },
              { type: "string", name: "location", label: "Location" },
              { type: "string", name: "description", label: "Description", ui: { component: "textarea" } },
              { type: "string", name: "impact", label: "Impact Summary", ui: { component: "textarea" } },
              {
                type: "string",
                name: "color",
                label: "Color Theme",
                options: [
                  "from-amber-500 to-orange-600",
                  "from-rose-500 to-pink-600",
                  "from-emerald-500 to-teal-600",
                  "from-purple-500 to-indigo-600",
                  "from-green-500 to-emerald-600",
                  "from-stone-600 to-stone-700",
                ],
              },
              { type: "string", name: "outcomes", label: "Outcomes", list: true },
            ],
          },
        ],
      },
    ],
  },
});
